name: flutter_mobx_gorouter
description: A simple Flutter app with MobX and GoRouter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0
  go_router: ^14.1.4
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  # Добавьте эти зависимости для работы с файлами:
  path_provider: ^2.1.3
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  open_file: ^3.3.3
  # Для работы с SharedPreferences (опционально):
  shared_preferences: ^2.2.2
  fl_chart: ^0.70.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true